export const TIMER_INCREASED = 'timerIncreased'
export const TIMER_DECREASED = 'timerDecreased'
export const TIMER_STARTED = 'timerStarted'
export const TIMER_STOPPED = 'timerStopped'
export const TIMER_RESET = 'timerReset'
export const LAP_CREATED = 'lapCreated'
